# Folder: bongard_solver/
# File: config.py
import torch
import os
import logging

logger = logging.getLogger(__name__)

# --- Global Device Configuration ---
# Automatically set device to GPU if available, otherwise CPU
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
logger.info(f"Using device: {DEVICE}")

# --- Image Normalization Constants (for ImageNet pretrained models) ---
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

# --- Feature Mapping Constants (for attributes and relations) ---
# These maps define the discrete classes for attributes and relations.
# Ensure these match the actual categories generated by your BongardGenerator
# and expected by your AttributeModel/RelationGNN.

ATTRIBUTE_SHAPE_MAP = {'circle': 0, 'square': 1, 'triangle': 2, 'pentagon': 3, 'star': 4}
ATTRIBUTE_COLOR_MAP = {'red': 0, 'blue': 1, 'green': 2, 'yellow': 3, 'purple': 4}
ATTRIBUTE_FILL_MAP = {'solid': 0, 'hollow': 1, 'striped': 2, 'dotted': 3}
ATTRIBUTE_SIZE_MAP = {'small': 0, 'medium': 1, 'large': 2}
ATTRIBUTE_ORIENTATION_MAP = {'upright': 0, 'inverted': 1, 'rotated_45': 2}
ATTRIBUTE_TEXTURE_MAP = {'none': 0, 'rough': 1, 'smooth': 2}

# Sum of all attribute classes for the AttributeModel's final head (if combined)
# Or, individual counts if separate heads are used (as in AttributeModel)
TOTAL_ATTRIBUTE_CLASSES = sum([
    len(ATTRIBUTE_SHAPE_MAP),
    len(ATTRIBUTE_COLOR_MAP),
    len(ATTRIBUTE_FILL_MAP),
    len(ATTRIBUTE_SIZE_MAP),
    len(ATTRIBUTE_ORIENTATION_MAP),
    len(ATTRIBUTE_TEXTURE_MAP)
])

RELATION_MAP = {
    'none': 0,
    'left_of': 1,
    'right_of': 2,
    'above': 3,
    'below': 4,
    'inside': 5,
    'outside': 6,
    'overlapping': 7,
    'touching': 8,
    'same_shape': 9,
    'same_color': 10,
    'same_size': 11,
    'different_shape': 12,
    'different_color': 13,
    'different_size': 14,
    'aligned_horizontal': 15,
    'aligned_vertical': 16,
}

# --- Conditional Feature Flags (for optional dependencies) ---
# These flags control whether certain features are enabled based on library availability.
# They are set to False by default and can be overridden if the libraries are detected.
# The `try-except` blocks in `models.py`, `training.py`, etc., handle their actual detection.
HAS_WANDB = False # Set to True if you have Weights & Biases installed and configured
HAS_TIMM_OPTIM = False # Set to True if `timm` optimizers are available (e.g., SophiaG)
HAS_TORCH_QUANTIZATION = True # Set to True if torch.quantization is fully functional
HAS_YOLO = True # Set to True if ultralytics (YOLOv8) is installed
HAS_SAM = True # Set to True if segment_anything is installed
HAS_PYG = True # Set to True if torch_geometric is installed
HAS_DALI = True # Set to True if nvidia-dali is installed
HAS_TOPO_FEATURES = True # Set to True if ripser and persim are installed
HAS_ATTENTION_UTILS = True # Set to True if attention_utils.py is present

# --- Main Configuration Dictionary ---
CONFIG = {
    # --- Data Loading & Preprocessing ---
    'data': {
        'image_size': 224,  # Standard input size for models (e.g., ResNet)
        'dataloader_workers': 4, # Number of CPU workers for PyTorch DataLoader (if DALI is false)
        'use_synthetic_data': True, # Whether to use synthetic data generation
        'synthetic_data_config': {
            'num_train_problems': 10000,
            'num_val_problems': 2000,
            'num_test_problems': 2000,
            'max_objects_per_image': 5,
            'max_support_images_per_problem': 5, # N_support for few-shot learning
            'min_objects_per_image': 1,
            'image_resolution': 256, # Resolution for generated images before resizing
            'problem_types': ['attribute_based', 'relational'], # Types of problems to generate
            'difficulty_levels': {'easy': 0.2, 'medium': 0.5, 'hard': 0.8}, # For curriculum learning
            'seed': 42 # Seed for synthetic data generation
        },
        'real_data_config': {
            'dataset_path': './data/real_bongard_problems', # Path to real Bongard problems
            'train_split': 0.8,
            'val_split': 0.1,
            'test_split': 0.1,
        },
        'use_dali': HAS_DALI, # Enable NVIDIA DALI for faster data loading/augmentation
        'dali': {
            'sample_per_gpu': 1, # Number of samples per GPU for DALI reader
            'sample_mode': 'random', # 'random' or 'sequential'
            'decode_device': 'mixed', # 'mixed' (GPU-accelerated) or 'cpu'
            'aug_device': 'gpu', # 'gpu' or 'cpu' for augmentation operations
            'output_dtype': 'float32', # Output data type for DALI processed images
            'output_layout': 'CHW', # Output image layout
            'mean': IMAGENET_MEAN, # Mean for normalization
            'std': IMAGENET_STD, # Std for normalization
            'crop_size': 224 # Crop size after resize
        }
    },

    # --- Object Detector Configuration (YOLO + SAM) ---
    'object_detector': {
        'yolo_pretrained': "yolov8s.pt", # Pretrained YOLOv8 model weights
        'fine_tune': True, # Whether to fine-tune YOLO on custom data
        'fine_tuned_weights': './checkpoints/yolo_fine_tuned.pt', # Path to save/load fine-tuned weights
        'yolo_data_yaml': "data/bongard_yolo.yaml", # YOLO dataset config file for fine-tuning
        'fine_tune_epochs': 10,
        'lr': 1e-3, # Learning rate for YOLO fine-tuning
        'batch_size': 16, # Batch size for YOLO fine-tuning
        'img_size': 224, # Image size for YOLO training
        'yolo_conf_threshold': 0.25, # Confidence threshold for YOLO detections
        'yolo_iou_threshold': 0.7, # IoU threshold for NMS
        'sam_model_type': 'vit_h', # SAM model type ('vit_h', 'vit_l', 'vit_b')
        'sam_checkpoint_path': 'checkpoints/sam_vit_h_4b8939.pth', # Path to SAM checkpoint
        'num_objects': 5 # Max number of objects to detect and process per image
    },

    # --- Model Architecture Configuration ---
    'model': {
        'backbone': "resnet50", # Feature extractor backbone: 'resnet50', 'mobilenet_v3_small', 'efficientnet_b0'
        'pretrained': True, # Use ImageNet pretrained weights for backbone
        'n_attributes': TOTAL_ATTRIBUTE_CLASSES, # Total number of attribute classes (sum of all individual attribute categories)
        
        'attribute_classifier_config': { # Individual attribute heads
            'shape': len(ATTRIBUTE_SHAPE_MAP),
            'color': len(ATTRIBUTE_COLOR_MAP),
            'fill': len(ATTRIBUTE_FILL_MAP),
            'size': len(ATTRIBUTE_SIZE_MAP),
            'orientation': len(ATTRIBUTE_ORIENTATION_MAP),
            'texture': len(ATTRIBUTE_TEXTURE_MAP)
        },
        
        'relation_gnn_config': {
            'hidden_dim': 128,
            'num_layers': 2,
            'num_relation_classes': len(RELATION_MAP),
            'dropout_prob': 0.1,
            'use_edge_features': False # Whether to use explicit edge features in GNN
        },
        
        'bongard_head_config': {
            'input_dim': 2048 + 128, # Example: ResNet50 feature dim (2048) + GNN global embedding dim (128)
            'hidden_dim': 256,
            'dropout_prob': 0.2,
            'num_classes': 2 # Binary classification: Positive (1) or Negative (0)
        },
        
        'MAX_GNN_OBJECTS': 5, # Maximum number of objects for GNN input (for padding)
        
        'simclr_config': {
            'enabled': True, # Enable SimCLR pretraining
            'projection_dim': 128, # Dimension of the SimCLR projection head output
            'temperature': 0.5, # Temperature for NT-Xent loss
            'pretrain_epochs': 20, # Number of epochs for SimCLR pretraining
            'pretrain_lr': 1e-4 # Learning rate for SimCLR pretraining
        },
        
        'support_set_encoder_config': {
            'enabled': True, # Enable support set encoding
            'encoder_type': 'deep_sets', # 'deep_sets' or 'set_transformer' or 'linear_attention_set_transformer'
            'input_dim': 2048, # Feature dimension of each object in the support set (e.g., from backbone)
            'hidden_dim': 256,
            'output_dim': 128, # Output dimension of the support set context vector
            'num_heads': 4, # For SetTransformer
            'num_blocks': 2 # For SetTransformer
        },
        
        'use_cross_attention': True, # Use cross-attention in BongardHead to integrate support context
        
        'use_persistent_homology': HAS_TOPO_FEATURES, # Enable Persistent Homology features
        'ph_feature_dim': 64, # Dimension of topological features
        'ph_pixel_thresh': 0.5, # Pixel threshold for converting mask to point cloud in topo_features.py
    },

    # --- Few-Shot Learning Configuration ---
    'few_shot': {
        'enable': True, # Enable few-shot learning paradigm (e.g., episodic training)
        'n_way': 2, # N-way classification (e.g., 2 for positive/negative in Bongard)
        'k_shot': 5, # K-shot (number of support examples per class)
        'q_query': 1, # Number of query examples per class
        'episodes': 10000, # Total number of episodes for training
        'episode_batch_size': 1 # Number of episodes per batch
    },

    # --- Training Configuration ---
    'training': {
        'epochs': 50,
        'batch_size': 16, # Effective batch size (per GPU if DDP)
        'num_workers': 4, # Number of workers for PyTorch DataLoader (if DALI is false)
        'seed': 42, # Random seed for reproducibility
        'learning_rate': 1e-4,
        'weight_decay': 1e-5, # L2 regularization
        'max_grad_norm': 1.0, # Gradient clipping to prevent exploding gradients (0.0 for no clipping)
        
        'optimizer': 'AdamW', # 'AdamW', 'SAM', 'SophiaG'
        'scheduler': 'CosineAnnealingLR', # 'CosineAnnealingLR', 'OneCycleLR', 'ReduceLROnPlateau'
        'scheduler_config': {
            'CosineAnnealingLR': {'eta_min': 1e-6},
            'OneCycleLR': {'max_lr': 1e-3, 'steps_per_epoch': 1000, 'epochs': 50}, # Example, adjust steps_per_epoch
            'ReduceLROnPlateau': {'mode': 'min', 'factor': 0.1, 'patience': 5}
        },
        
        'use_amp': True, # Automatic Mixed Precision (FP16)
        'use_sam': True, # Sharpness-Aware Minimization (SAM) optimizer
        'sam_rho': 0.05, # Rho parameter for SAM optimizer
        
        'use_swa': True, # Stochastic Weight Averaging (SWA)
        'swa_start_epoch': 30, # Epoch to start applying SWA
        'swa_lr': 5e-5, # Learning rate for SWA
        
        'use_mixup_cutmix': True, # Data augmentation with MixUp or CutMix
        'mixup_alpha': 0.8,
        'cutmix_alpha': 1.0,
        'mixup_prob': 0.5, # Probability of applying MixUp (if use_mixup_cutmix is true)
        'cutmix_prob': 0.5, # Probability of applying CutMix (if use_mixup_cutmix is true)
        'label_smoothing': 0.1, # Label smoothing for classification losses
        
        'curriculum_learning': True, # Enable curriculum learning (e.g., difficulty sampling)
        'curriculum_config': {
            'difficulty_sampling': True, # Use Prioritized Experience Replay (PER) for difficulty
            'difficulty_update_frequency_batches': 10, # How often to update priorities in PER
            'per_alpha': 0.6, # Alpha parameter for PER (how much prioritization)
            'per_beta_start': 0.4, # Initial beta parameter for PER (importance sampling correction)
            'per_beta_end': 1.0 # Final beta parameter for PER
        },
        
        'consistency_loss_weight': 1.0, # Overall weight for consistency losses
        'feature_consistency_weight': 0.5, # Weight for feature consistency loss
        'symbolic_consistency_weight': 0.5, # Weight for symbolic consistency loss
        'relation_loss_weight': 1.0, # Weight for relation classification loss
        
        'use_knowledge_distillation': False, # Enable knowledge distillation from teacher ensemble
        'distillation_config': {
            'temperature': 2.0, # Temperature for soft targets
            'alpha': 0.5, # Weight for soft targets vs. hard targets
            'ensemble_dropout_prob': 0.2, # Dropout rate for teacher models during distillation
            'use_mask_distillation': False, # Mask distillation based on teacher agreement
            'mask_agreement_threshold': 0.9 # Agreement threshold for mask
        },
        
        'use_rl_reformulation': False, # Enable RL-based rule search
        'rl_config': {
            'num_episodes': 100, # Number of RL episodes
            'policy_lr': 1e-4, # Learning rate for RL policy network
            'max_steps_per_episode': 10, # Max steps in an RL episode
            'gamma': 0.99, # Discount factor for RL rewards
            'entropy_coeff': 0.01 # Entropy regularization coefficient for RL
        },

        # --- Pruning Configuration ---
        'pruning': {
            'enabled': False, # Enable model pruning
            'method': "ln_structured", # 'l1_unstructured', 'random_unstructured', 'ln_structured'
            'amount': 0.2, # Amount of pruning (e.g., 0.2 means 20% pruned)
            'use_sensitivity': True, # Use sensitivity analysis to guide pruning
            'pruning_target_layers_ratio': 0.5, # Ratio of least sensitive layers to target for pruning
            'iterations': 2, # Number of pruning iterations
            'fine_tune_epochs_per_iter': 3, # Epochs to fine-tune after each pruning iteration
            'prune_interval_epochs': 10, # Apply pruning every N epochs (if enabled)
            'checkpoint': './checkpoints/best_bongard_model.pth' # Checkpoint for pruning (if loading a specific one)
        },

        # --- Quantization Configuration ---
        'quantization': {
            'qat': False, # Quantization Aware Training
            'ptq': False, # Post-Training Quantization
            'calibration_batches': 10, # Number of batches for PTQ calibration
            'export_quantized_model': False, # Export the quantized model (ONNX/TorchScript)
        },
        
        # --- Logging and Checkpointing ---
        'validation_frequency_batches': 50, # Validate every N batches
        'log_interval_batches': 10, # Log training metrics every N batches
    },

    # --- Debugging & Logging ---
    'debug': {
        'log_level': 'INFO', # DEBUG, INFO, WARNING, ERROR, CRITICAL
        'save_model_checkpoints': './checkpoints', # Directory to save model checkpoints
        'save_grad_cam_outputs': './grad_cam_outputs', # Directory to save Grad-CAM visualizations
        'rule_eval_log_interval_batches': 100, # Log rule evaluation results every N batches
    },

    # --- Ensemble Configuration (for Knowledge Distillation) ---
    'ensemble': {
        'num_members': 3, # Number of teacher models in the ensemble
        'train_members': True, # Whether to train ensemble members (teachers) or load them
        'teacher_model_paths': [] # Paths to pre-trained teacher models if not training
    }
}

def load_config(config_path: str = None) -> Dict[str, Any]:
    """
    Loads configuration from a YAML file if path is provided,
    otherwise returns the default CONFIG dictionary.
    
    Args:
        config_path (str, optional): Path to a YAML configuration file. Defaults to None.
    
    Returns:
        Dict[str, Any]: The loaded or default configuration dictionary.
    """
    if config_path:
        try:
            import yaml
            with open(config_path, 'r') as f:
                loaded_config = yaml.safe_load(f)
            # Merge loaded config with default, allowing loaded to override
            # This is a simple merge; for deep merge, a utility function is needed.
            CONFIG.update(loaded_config)
            logger.info(f"Configuration loaded from {config_path}")
        except ImportError:
            logger.warning("PyYAML not found. Cannot load config from YAML file. Using default CONFIG.")
        except FileNotFoundError:
            logger.warning(f"Config file not found at {config_path}. Using default CONFIG.")
        except Exception as e:
            logger.error(f"Error loading config from {config_path}: {e}. Using default CONFIG.")
    
    # Ensure flags are correctly set based on their actual availability
    # (These are typically set by try-except blocks in modules, but can be
    # initialized here for consistency if not dynamic)
    global HAS_WANDB, HAS_TIMM_OPTIM, HAS_TORCH_QUANTIZATION, HAS_YOLO, HAS_SAM, HAS_PYG, HAS_DALI, HAS_TOPO_FEATURES, HAS_ATTENTION_UTILS
    
    # These checks would ideally be performed once at startup in main.py or a dedicated setup script
    # and then passed to config.py. For a self-contained config.py, we can put dummy checks here.
    try:
        import wandb
        HAS_WANDB = True
    except ImportError:
        HAS_WANDB = False
    
    try:
        import torch_optimizer
        HAS_TIMM_OPTIM = True # Assuming torch_optimizer covers this
    except ImportError:
        HAS_TIMM_OPTIM = False
        
    try:
        import torch.quantization as tq
        HAS_TORCH_QUANTIZATION = True
    except ImportError:
        HAS_TORCH_QUANTIZATION = False

    try:
        from ultralytics import YOLO
        HAS_YOLO = True
    except ImportError:
        HAS_YOLO = False

    try:
        from segment_anything import sam_model_registry
        HAS_SAM = True
    except ImportError:
        HAS_SAM = False

    try:
        import torch_geometric
        HAS_PYG = True
    except ImportError:
        HAS_PYG = False

    try:
        import nvidia.dali
        HAS_DALI = True
    except ImportError:
        HAS_DALI = False
    
    try:
        import ripser, persim
        HAS_TOPO_FEATURES = True
    except ImportError:
        HAS_TOPO_FEATURES = False

    try:
        from attention_utils import cross_attend # Assuming this module exists
        HAS_ATTENTION_UTILS = True
    except ImportError:
        HAS_ATTENTION_UTILS = False

    # Update CONFIG based on actual library availability
    CONFIG['data']['use_dali'] = HAS_DALI
    CONFIG['model']['use_persistent_homology'] = HAS_TOPO_FEATURES
    CONFIG['model']['use_cross_attention'] = CONFIG['model']['use_cross_attention'] and HAS_ATTENTION_UTILS # Only if requested AND module exists
    # Object detector and GNN will check HAS_YOLO, HAS_SAM, HAS_PYG internally

    return CONFIG

# Call load_config once to initialize CONFIG and feature flags when config.py is imported
CONFIG = load_config()

