# Bongard Solver Config Template (YAML)
# This file contains all generator and dataset parameters required by generator.py and the pipeline.

# --- Device Configuration ---
device: cuda  # or 'cpu'

# --- Data Configuration ---
data:
  image_size: [224, 224]
  num_channels: 3
  use_synthetic_data: true
  data_root_path: ./data
  dataloader_workers: 4
  total: 1000  # Total examples for hybrid generation
  hybrid_split:
    cp: 0.7
    ga: 0.3
  synthetic_data_config:
    num_train_problems: 10000
    num_val_problems: 1000
    min_objects_per_image: 1
    max_objects_per_image: 5
    object_size_range: [20, 80]
    padding: 10
    font_path: null
    scene_layout_types: [random, grid, polar]
    min_support_images_per_problem: 2
    max_support_images_per_problem: 5
    synthetic_samples: 1000
    use_background_textures: true
    background_texture_path: ./data/textures
    background_texture_alpha_range: [0.1, 0.5]
    use_jitter: true
    jitter_strength_range: [0.5, 2.0]
    use_occluders: true
    occluder_count_range: [1, 3]
    occluder_size_range: [10, 50]
    occluder_color_range:
      - [0, 255]
      - [0, 255]
      - [0, 255]
    use_blur: true
    blur_radius_range: [0.5, 2.0]
    confidence_decay_rate: 0.05
  real_data_path: ./data/real_bongard
  real_data_config:
    dataset_name: bongard_dataset_v1
    dataset_path: ./data/real_bongard
    train_split: 0.8
  use_dali: false
  dali_augmentations:
    jpeg_p: 0.1
    jpeg_q: [50, 100]
    gaussian_blur_p: 0.1
    gaussian_blur_sigma_range: [0.1, 2.0]
    color_twist_p: 0.1
    color_twist_brightness_range: [0.8, 1.2]
    color_twist_contrast_range: [0.8, 1.2]
    color_twist_saturation_range: [0.8, 1.2]
    color_twist_hue_range: [-0.1, 0.1]
  initial_image_size: [112, 112]
  progressive_resizing_epochs: 5
  curriculum_learning_enabled: true
  curriculum_difficulty_metric: std_dev
  curriculum_annealing_epochs: 5
  cache_data: true
  curriculum_start_difficulty: 0.0
  curriculum_end_difficulty: 1.0
  curriculum_difficulty_schedule: linear
  curriculum_update_interval_epochs: 1
  class_imbalance_threshold: 0.2

# --- Add all other config sections as needed (see config.py for full structure) ---
# training:
# model:
# debug:
# paths:
# ...
